site_name: ControlPage Documentation
repo_url: https://gitlab.com/controlpage/controlpage-docs
edit_uri: -/edit/main/docs/
repo_name: controlpage/controlpage-docs

theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab

  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

plugins:
  - glightbox

extra:
  social:
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.fischerserver.eu/controlpage

copyright: Copyright &copy; 2020 - 2023 Simon Fischer and contributors (licensed under MIT)

nav:
  - Home: index.md
  - FAQ: faq.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Terminology: getting-started/terminology.md
    - Creating your first view: getting-started/create-view.md
    - Features: getting-started/features.md
    - Settings: getting-started/settings.md
    - NodeCG-Integration: getting-started/nodecg-integration.md
  - Contribute:
    - Basics: contribute/basics.md
    - Roadmap: contribute/roadmap.md
  - Advanced:
    - Setting up a Reverse Proxy: advanced/reverse-proxy.md